name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}${buildNo}
authors: [Frank Baumann, Milan Albrecht, Tobias Schmitz, Daniel Saukel]
description: ${project.description}
website: ${project.url}
softdepend: [CommandsXL, ItemsXL, Vault, Citizens, CustomMobs, InsaneMobs, MythicMobs, Parties, HolographicDisplays, LWC, PlaceholderAPI]
commands:
  dungeonsxl:
    description: Reference command for DungeonsXL.
    aliases: [dxl,dungeon]
api-version: 1.13
